name: style

on:
  push: {branches: [main]} # pushes to main
  pull_request: {} # all PRs

jobs:
  mypy:
    # mypy results differ based on the python version, so run on multiple ones
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.12']

    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install -e . --group typecheck
        pip install -r requirements.txt

    - name: MyPy
      run: 'mypy py'

  ruff:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}
    env:
      runtag: ${{ matrix.os }}-${{ matrix.python-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -e . --group lint

    - name: Ruff
      run: 'ruff check --output-format=github py'
